name: Build, Deploy to AWS
on: 
  workflow_dispatch:
  pull_request:
    branches:
      - "prod"
    types: [opened, edited, reopened]
permissions:
  contents: write
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Build
        # env:
        #   NEXT_PUBLIC_URL_BACKEND: ${{ secrets.BACK_URL }}
        run: |
          npm i
          npm run build
          touch out/.nojekyll
        # Tests will be here
      # - name: Deploy
      #   # https://github.com/JamesIves/github-pages-deploy-action
      #   uses: JamesIves/github-pages-deploy-action@v4.5.0
      #   with:
      #     branch: gh-pages
      #     folder: out
      - name: Deploy to EC2
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete --exclude="node_modules" --exclude=".env.*" --exclude=".next" --exclude="*.pem" --filter=""
          path: /
          remote_path: /home/ubuntu/datemarks/app
          remote_host: ${{ secrets.EC2_HOST }}
          remote_user: ${{ secrets.EC2_USERNAME }}
          remote_key: ${{ secrets.EC2_SSH_KEY }}
      - name: Update on EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOSTNAME: ${{secrets.EC2_HOST}}
          USER_NAME: ${{secrets.EC2_USERNAME}}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

              # Now we have got the access of EC2 and we will start the deploy .
              cd /home/ubuntu/datemarks &&
              sudo chmod -R 777 ./app &&
              cd /home/ubuntu/datemarks/app &&
              npm i &&
              echo Deps installed &&
              pm2 delete --silent datemarks_ci-cd --watch || true &&
              echo pm2: datemarks_ci-cd removed to be updated &&
              pm2 start --name datemarks_ci-cd npm --run server_ci-cd --update-env &&
              echo pm2: new datemarks_ci-cd installed &&
              pm2 save &&
              echo Finish
              '
